### ISSUE TITLE
Bug: error in `gvar.raniter` with negative `svdcut`

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#26]
In the following code I define very correlated gvars and try to take samples from them.

```python
import gvar
import numpy as np

x = np.linspace(0, 1, 1000)
cov = np.exp(-(x[None, :] - x[:, None]) ** 2)
y = gvar.gvar(np.zeros(len(x)), cov)

gvar.sample(y) # no problem
gvar.svd(y, svdcut=-1e-12) # no problem
gvar.sample(y, svdcut=-1e-12) # fails
```

Output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_utilities.pyx", line 2319, in gvar._utilities.sample
  File "_utilities.pyx", line 2374, in raniter
IndexError: index 9 is out of bounds for axis 0 with size 9
```

I need the negative cut because the positive one introduces a bit of noise in my samples.

**Comment by gplepage** [comment]
Fixed in v11.9.7. Thanks.
