### ISSUE TITLE
Bug: unexpected attribute access in `BufferDict.del_distribution`

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#29]
Deleting a distribution produces an `AttributeError` if `BufferDict.uniform` has not been previously called, but not always, I'm not sure this bug is fully reproducible. Anyway:

```python
import gvar
gvar.BufferDict.del_distribution('log')
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_bufferdict.pyx", line 539, in gvar._bufferdict.BufferDict.del_distribution
AttributeError: 'cython_function_or_method' object has no attribute 'invfcn'
```

Despite the error, the distribution has been deleted:

```python
gvar.BufferDict.del_distribution('log')
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_bufferdict.pyx", line 538, in gvar._bufferdict.BufferDict.del_distribution
KeyError: 'log'
```

Using `uniform` solves the problem:

```python
gvar.BufferDict.uniform('U', 0, 1)
gvar.BufferDict.del_distribution('sqrt') # -> all fine
```

Looking at the code of `del_distribution`, it would seem legal:

```python
    @staticmethod
    def del_distribution(name):
        """ Delete |BufferDict| distribution ``name``. 
        
        Raises a ``ValueError`` if ``name`` is not the name of 
        an existing distribution.
        """
        if name in BufferDict.invfcn:
            del BufferDict.invfcn[name]
        else:
            raise ValueError('{} is not a distribution'.format(name))
        if hasattr(BufferDict.uniform, 'invfcn') and name in BufferDict.uniform.invfcn:
            del BufferDict.uniform.invfcn[name]
        BufferDict._ver_g += 1
```

My guess is that, either in the C transpiling or in the compilation proper, the compiler does not respect the non-evaluation of the second operand in the `and` and accesses `BufferDict.uniform.invfcn` even though the `hasattr` test failed.

**Comment by Gattocrucco** [comment]
Wait, I found the problem and it was my fault: I used a different python installation with an old version of gvar, it's an old bug.
