### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'gvar._svec_smat.smat'

### ISSUE THREAD

**Issue by gothicVI** [gplepage/gvar#36]
Hi,

we have a pickle file that was written with `gvar==11.10` and can no longer be read with `gvar==11.11.10`.
Reverting back to the older version works.
The structure of the pickle file is `dict[str, dict[str, gvar]]`, where when printing the dict after reading the `gvar` values are displayed as, e.g., `0.01224(37)`.

The error displayed when trying to read the pickle dump with the current `gvar` version is:
```
Traceback (most recent call last):
  File "src/gvar/_gvarcore.pyx", line 1066, in gvar._gvarcore.GVarFactory._call3
TypeError: float() argument must be a string or a number, not 'gvar._svec_smat.smat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./load_old.py", line 12, in <module>
    my_dict = pickle.load(fp)
  File "src/gvar/_gvarcore.pyx", line 77, in gvar._gvarcore.GVar.__setstate__
  File "src/gvar/_gvarcore.pyx", line 981, in gvar._gvarcore.GVarFactory.__call__
  File "src/gvar/_gvarcore.pyx", line 1068, in gvar._gvarcore.GVarFactory._call3
TypeError: Value not a number.
```
where the python file reads:
```
#!/usr/bin/env python3

import pickle

import gvar as gv

for dict_file_name in [
    'file1.p',
    'file2.p'
]:
    with open(dict_file_name, 'rb') as fp:
        my_dict = pickle.load(fp)
    print(my_dict)
```

**Comment by gplepage** [comment]
The newly posted version 11.11.11 should fix this.

**Comment by gothicVI** [comment]
Thanks so much!
